services:
  postgres:
    container_name: "event-report-postgres"
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=event_report'
      - 'POSTGRES_PASSWORD=12345'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"
